// cloudfunctions/reminders/index.js
// 今日提醒云函数 —— 家属为老人管理提醒（增删改查、自动提醒、状态跟踪）

const cloud = require('wx-server-sdk')
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })

const db = cloud.database()
const _ = db.command

const COL        = 'reminder_templates'
const COL_DONE   = 'reminder_done'
const COL_SETTINGS = 'reminder_settings'

// 自动提醒默认模板
const DEFAULT_TEMPLATES = [
  { icon: '💊', title: '早上用药提醒', time: '08:00', type: 'medication', note: '' },
  { icon: '🚶', title: '下午散步提醒', time: '15:00', type: 'walk',       note: '' },
  { icon: '💊', title: '晚上用药提醒', time: '20:00', type: 'medication', note: '' }
]

// ── 工具函数 ──────────────────────────────────────────

function normalizeTime(t) {
  if (typeof t !== 'string') return ''
  const m = t.trim().match(/^([01]?\d|2[0-3]):([0-5]\d)$/)
  if (!m) return ''
  return `${m[1].padStart(2, '0')}:${m[2]}`
}

function todayKey() {
  const d = new Date()
  return `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`
}

function getCurrentMinutes() {
  const now = new Date()
  return now.getHours() * 60 + now.getMinutes()
}

/** 根据调用者角色找到目标老人的 openid */
async function findElderlyOpenid(callerOpenid, role) {
  if (role === 'elderly') return callerOpenid
  const { data } = await db.collection('bindings')
    .where({ fromOpenid: callerOpenid }).limit(1).get()
  if (!data.length) return null

  const binding = data[0]
  // toOpenid 已有值，直接返回
  if (binding.toOpenid) return binding.toOpenid

  // toOpenid 为空但 toPhone 存在，用手机号在 elderly 集合中查找并回填
  if (binding.toPhone) {
    const { data: elders } = await db.collection('elderly')
      .where({ phone: binding.toPhone }).limit(1).get()
    if (elders.length > 0 && elders[0]._openid) {
      await db.collection('bindings').doc(binding._id)
        .update({ data: { toOpenid: elders[0]._openid } }).catch(() => {})
      return elders[0]._openid
    }
  }
  return null
}

// ── getTemplates ─────────────────────────────────────

async function getTemplates(callerOpenid, role) {
  const eid = await findElderlyOpenid(callerOpenid, role)
  if (!eid) return { code: 0, data: [], msg: '未绑定老人账号' }

  // 读取自动提醒设置
  const { data: sList } = await db.collection(COL_SETTINGS)
    .where({ elderlyOpenid: eid }).limit(1).get()
  const autoRemind = sList.length > 0 ? sList[0].autoRemind : false

  const query = { elderlyOpenid: eid }
  if (!autoRemind) query.autoGenerated = _.neq(true) // 关闭时隐藏自动模板

  const { data } = await db.collection(COL)
    .where(query).orderBy('time', 'asc').limit(50).get()

  return { code: 0, data: data.map(d => ({ ...d, id: d._id })) }
}

// ── addTemplate ──────────────────────────────────────

async function addTemplate(callerOpenid, role, { title, time, icon, type, note }) {
  const nt = normalizeTime(time)
  if (!title || !nt) return { code: 1, msg: '缺少标题或时间（HH:mm）' }

  const eid = await findElderlyOpenid(callerOpenid, role)
  if (!eid) return { code: 1, msg: '未绑定老人账号，请先关联' }

  // 时间冲突检查
  const { total } = await db.collection(COL)
    .where({ elderlyOpenid: eid, time: nt }).count()
  if (total > 0) return { code: 1, msg: '该时间已存在提醒，请修改时间' }

  const now = new Date()
  const doc = {
    elderlyOpenid: eid,
    createdByOpenid: callerOpenid,
    createdByRole: role,
    icon: icon || '⏰',
    title: String(title).trim(),
    time: nt,
    type: type || 'custom',
    note: note ? String(note).trim().slice(0, 50) : '',
    autoGenerated: false,
    createdAt: now,
    updatedAt: now
  }
  const res = await db.collection(COL).add({ data: doc })
  doc._id = res._id
  doc.id = res._id
  return { code: 0, data: doc }
}

// ── updateTemplate ───────────────────────────────────

async function updateTemplate(callerOpenid, role, { templateId, title, time, icon, type, note }) {
  if (!templateId) return { code: 1, msg: '缺少 templateId' }

  const eid = await findElderlyOpenid(callerOpenid, role)
  const update = { updatedAt: new Date() }

  if (icon !== undefined)  update.icon  = icon || '⏰'
  if (title !== undefined) update.title = String(title).trim()
  if (type !== undefined)  update.type  = type
  if (note !== undefined)  update.note  = String(note).trim().slice(0, 50)

  if (time !== undefined) {
    const nt = normalizeTime(time)
    if (!nt) return { code: 1, msg: '时间格式应为 HH:mm' }
    // 时间冲突检查（排除自身）
    if (eid) {
      const { data: conflicts } = await db.collection(COL)
        .where({ elderlyOpenid: eid, time: nt, _id: _.neq(templateId) }).limit(1).get()
      if (conflicts.length) return { code: 1, msg: '该时间已存在提醒，请修改时间' }
    }
    update.time = nt
  }

  await db.collection(COL).doc(templateId).update({ data: update })
  return { code: 0, msg: '已更新' }
}

// ── deleteTemplate ───────────────────────────────────

async function deleteTemplate(callerOpenid, role, { templateId }) {
  if (!templateId) return { code: 1, msg: '缺少 templateId' }
  await db.collection(COL).doc(templateId).remove()
  return { code: 0, msg: '已删除' }
}

// ── batchDelete ──────────────────────────────────────

async function batchDelete(callerOpenid, role, { templateIds }) {
  if (!templateIds || !templateIds.length) return { code: 1, msg: '请选择要删除的提醒' }
  let deleted = 0
  for (const id of templateIds) {
    try { await db.collection(COL).doc(id).remove(); deleted++ } catch (e) { /* skip */ }
  }
  return { code: 0, msg: `已删除 ${deleted} 项` }
}

// ── getToday ─────────────────────────────────────────

async function getToday(callerOpenid, role) {
  const eid = await findElderlyOpenid(callerOpenid, role)
  if (!eid) return { code: 0, data: [] }

  // 自动提醒过滤
  const { data: sList } = await db.collection(COL_SETTINGS)
    .where({ elderlyOpenid: eid }).limit(1).get()
  const autoRemind = sList.length > 0 ? sList[0].autoRemind : false

  const query = { elderlyOpenid: eid }
  if (!autoRemind) query.autoGenerated = _.neq(true)

  const { data: templates } = await db.collection(COL)
    .where(query).orderBy('time', 'asc').limit(50).get()

  const nowMinutes = getCurrentMinutes()
  const date = todayKey()

  // 读取手动标记记录
  const { data: doneRecords } = await db.collection(COL_DONE)
    .where({ elderlyOpenid: eid, date }).get()
  const doneMap = {}
  for (const r of doneRecords) doneMap[r.templateId] = r.done

  const today = templates.map(t => {
    const parts = normalizeTime(t.time).split(':').map(Number)
    const reminderMinutes = parts[0] * 60 + parts[1]
    // 手动标记优先，否则按时间自动判定
    const reminded = (doneMap[t._id] !== undefined) ? doneMap[t._id] : (nowMinutes >= reminderMinutes)
    return {
      id: `${date}-${t._id}`,
      templateId: t._id,
      icon: t.icon || '⏰',
      title: t.title || '提醒',
      time: t.time || '',
      type: t.type || 'custom',
      note: t.note || '',
      reminded,
      done: reminded,
      statusText: reminded ? '已提醒' : '未提醒'
    }
  })
  return { code: 0, data: today }
}

// ── toggleDone（手动标记已提醒/未提醒）───────────────

async function toggleDone(callerOpenid, role, { templateId, done }) {
  const eid = await findElderlyOpenid(callerOpenid, role)
  if (!eid) return { code: 1, msg: '未找到关联老人' }

  const date = todayKey()
  const { data: existing } = await db.collection(COL_DONE)
    .where({ elderlyOpenid: eid, date, templateId }).limit(1).get()

  if (existing.length) {
    await db.collection(COL_DONE).doc(existing[0]._id).update({
      data: { done: !!done, markedByOpenid: callerOpenid, markedAt: new Date() }
    })
  } else {
    await db.collection(COL_DONE).add({
      data: { elderlyOpenid: eid, templateId, date, done: !!done, markedByOpenid: callerOpenid, markedAt: new Date() }
    })
  }
  return { code: 0, msg: done ? '已标记为已提醒' : '已标记为未提醒' }
}

// ── getAutoRemindSetting ─────────────────────────────

async function getAutoRemindSetting(callerOpenid, role) {
  const eid = await findElderlyOpenid(callerOpenid, role)
  if (!eid) return { code: 0, data: { autoRemind: false } }
  const { data } = await db.collection(COL_SETTINGS)
    .where({ elderlyOpenid: eid }).limit(1).get()
  return { code: 0, data: { autoRemind: data.length > 0 ? data[0].autoRemind : false } }
}

// ── toggleAutoRemind ─────────────────────────────────

async function toggleAutoRemind(callerOpenid, role, { enabled }) {
  const eid = await findElderlyOpenid(callerOpenid, role)
  if (!eid) return { code: 1, msg: '未绑定老人账号' }

  // 更新/创建设置
  const { data: sList } = await db.collection(COL_SETTINGS)
    .where({ elderlyOpenid: eid }).limit(1).get()
  const now = new Date()
  if (sList.length) {
    await db.collection(COL_SETTINGS).doc(sList[0]._id).update({
      data: { autoRemind: !!enabled, updatedAt: now }
    })
  } else {
    await db.collection(COL_SETTINGS).add({
      data: { elderlyOpenid: eid, autoRemind: !!enabled, createdAt: now, updatedAt: now }
    })
  }

  // 开启时创建默认模板（不存在才创建）
  if (enabled) {
    for (const tpl of DEFAULT_TEMPLATES) {
      const { total } = await db.collection(COL)
        .where({ elderlyOpenid: eid, autoGenerated: true, title: tpl.title }).count()
      if (total === 0) {
        await db.collection(COL).add({
          data: {
            ...tpl, elderlyOpenid: eid,
            createdByOpenid: callerOpenid, createdByRole: role,
            autoGenerated: true, createdAt: now, updatedAt: now
          }
        })
      }
    }
  }
  return { code: 0, msg: enabled ? '已开启自动提醒' : '已关闭自动提醒' }
}

// ── 入口 ──────────────────────────────────────────────

exports.main = async (event) => {
  try {
    const { OPENID } = cloud.getWXContext()
    const { action, role = 'family', ...params } = event
    console.log('[reminders] action:', action, 'role:', role, 'openid:', OPENID)

    switch (action) {
      case 'getTemplates':        return await getTemplates(OPENID, role)
      case 'addTemplate':         return await addTemplate(OPENID, role, params)
      case 'updateTemplate':      return await updateTemplate(OPENID, role, params)
      case 'deleteTemplate':      return await deleteTemplate(OPENID, role, params)
      case 'batchDelete':         return await batchDelete(OPENID, role, params)
      case 'getToday':            return await getToday(OPENID, role)
      case 'toggleDone':          return await toggleDone(OPENID, role, params)
      case 'getAutoRemindSetting': return await getAutoRemindSetting(OPENID, role)
      case 'toggleAutoRemind':    return await toggleAutoRemind(OPENID, role, params)
      default:                    return { code: -1, msg: '未知 action' }
    }
  } catch (err) {
    console.error('[reminders] error:', err)
    return { code: -2, msg: err.message || '服务异常' }
  }
}
